name: CD

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - run: |
          python -m pip install -U pip
          pip install setup.py bdist_wheel

      - run: python setup.py bdist_wheel
